version: '3'

services:
  reverse-proxy:
    networks:
        - ring
    ports:
        - 80:80
    build: 
      context: ./reverse-proxy
    volumes:
        - ./reverse-proxy/conf/includes:/etc/nginx/includes
        - ./reverse-proxy/html:/etc/static
    depends_on:
        - frontend
    extra_hosts:
        - host.docker.internal:host-gateway
  frontend:
    image: microlc/micro-lc:latest
    hostname: fe-container
    networks:
        - ring
  composer:
    hostname: composer
    networks:
      - ring
    image: microlc/micro-lc-element-composer:latest
    environment:
      - HTTP_PORT=8080
  back-kit:
    hostname: back-kit
    networks:
      - ring
    image: nexus.mia-platform.eu/backoffice/bk-web-components:${BACK_KIT_VERSION:-unstable}
    environment:
      - HTTP_PORT=8080
  notification-center:
    hostname: notification-center
    networks:
      - ring
    image: microlc/micro-lc-notification-center:2.0.0-rc1
    environment:
      - HTTP_PORT=8080

networks:
    ring:
